---
sidebar: sidebar 
permalink: install-setup/cable-hardware.html 
keywords: asa r2, aff a1k, aff a70, aff a90, aff c80, asa a1k, asa a90, asa a70, asa a30, asa a20, asa a50, asa c30 cable controllers 
summary: ASA r2ストレージシステムをケーブル接続して、クラスタ通信、ホストネットワーク アクセス、管理接続、およびストレージシェルフ接続を有効にします。 
---
= ASA R2ストレージシステムのハードウェアのケーブル接続
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2ストレージシステムをケーブル接続して、クラスタ通信、ホストネットワーク アクセス、管理接続、およびストレージシェルフ接続を有効にします。



== ハードウェアケーブル配線の概要

ケーブル配線はプラットフォームモデルによって異なります。ASA r2モデルは、独自のスロット位置、ポート割り当て、およびI/Oモジュール構成を備えています。ASA r2モデルの手順を選択してください：

* link:cable-hardware-a1k.html["ケーブルASA A1K"]
* link:cable-hardware-a70-90.html["ケーブルASA A70およびA90"]
* link:cable-hardware-a20-30-50.html["ケーブルASA A20、A30、A50"]
* link:cable-hardware-c30.html["ケーブルASA C30"]


ハードウェア配線では、4種類の接続をケーブルで行います：

* *クラスター/ HA 接続*
+
2つのコントローラを相互に接続する（スイッチレスクラスタ）か、クラスタネットワーク スイッチに接続する（スイッチドクラスタ）。これらの接続により、コントローラペア間でのクラスタ通信と高可用性フェイルオーバーが可能になります。クラスタインターコネクトトラフィックとHAトラフィックは、同じ物理ポートを共有します。

* *ホスト ネットワーク接続*
+
ホスト構成に応じて、イーサネット（iSCSI、NVMe/TCP）またはファイバチャネル（FC、NVMe/FC）を使用してコントローラをSANホストに接続します。これらの接続により、ストレージワークロードへのデータアクセスが可能になります。

* *管理ネットワーク接続*
+
ONTAP System ManagerとCLIを使用したシステム管理アクセスを行うには、コントローラを管理ネットワークに接続します。

* *ストレージシェルフの接続*
+
コントローラをNS224ストレージシェルフに接続して、システムのストレージ容量を提供します。





== その他のリソース

配線手順には、一般的な構成例が示されています。具体的なケーブルの種類は、ストレージシステム用に注文したコンポーネントによって異なります。包括的な構成とスロット優先順位の詳細については、link:https://hwu.netapp.com["NetApp Hardware Universe"^]を参照してください。
