---
sidebar: sidebar 
permalink: install-setup/deploy-hardware.html 
keywords: asa r2, install hardware, deploy hardware, aff a1k, aff a70, aff a90, aff c80, asa a1k, asa a90, asa a70 
summary: ASA R2ストレージシステムおよびストレージシェルフ用のレールキットを設置し、ASA R2ハードウェアをキャビネットまたはTelcoラックに固定する方法について説明します。 
---
= ASA R2ストレージシステムのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA R2ストレージシステムの設置準備が完了したら、システムのハードウェアを設置します。まず、レールキットを取り付けます。次に、ストレージシステムをキャビネットまたはTelcoラックに設置して固定します。

.開始する前に
* レールキットに手順書が同梱されていることを確認します。
* ストレージシステムとストレージシェルフの重量に関連する安全上の問題に注意してください。
* ストレージ・システム内の通気は'ベゼルまたはエンド・キャップが取り付けられている前面から入り'ポートが取り付けられている背面から排出されます


.手順
. キットに付属の手順書に従って、ストレージシステムとストレージシェルフのレールキットを必要に応じて設置します。
. キャビネットまたはTelcoラックにストレージシステムを設置して固定します。
+
.. キャビネットまたはTelcoラックの中央にあるレールにストレージシステムを配置し、ストレージシステムを下から支えて所定の位置にスライドさせます。
.. 付属の取り付けネジを使用して、ストレージシステムをキャビネットまたはTelcoラックに固定します。


. ストレージシェルフを設置します。
+
.. ストレージシェルフの背面をレールに合わせ、シェルフを下から支えてキャビネットまたはTelcoラックに挿入します。
+
複数のストレージシェルフを設置する場合は、最初のストレージシェルフをコントローラの真上に配置します。2台目のストレージシェルフをコントローラの真下に置きます。ストレージシェルフを追加する場合は、このパターンを繰り返します。

.. 付属の取り付けネジを使用して、ストレージシェルフをキャビネットまたはTelcoラックに固定します。


. ケーブルマネジメントデバイスをストレージシステムの背面に接続します。
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[ケーブルマネジメントデバイスの取り付け]

. ベゼルをストレージシステムの前面に取り付けます。


.次の手順
ASA R2システムのハードウェアの設置が完了したら、次のlink:cable-hardware.html["ASA R2システムのコントローラとストレージシェルフをケーブル接続"]手順を実行します。
