---
sidebar: sidebar 
permalink: install-setup/initialize-ontap-cluster.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, initialize cluster, set up cluster, ontap 
summary: System Managerを使用してASA R2システムにONTAPクラスタをセットアップする方法について説明します。 
searchtitle: ONTAPシステムマネージャを使用したONTAPクラスタのセットアップ| ASA R2 
---
= ASA R2ストレージシステムでのONTAPクラスタのセットアップ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerの手順に従って、ONTAP ASA R2クラスタのセットアップワークフローをすばやく簡単に実行できます。

クラスタのセットアップ時に、デフォルトのデータStorage Virtual Machine（VM）が作成されます。必要に応じて、Domain Name System（DNS；ドメインネームシステム）を有効にしてホスト名を解決したり、Network Time Protocol（NTP；ネットワークタイムプロトコル）を使用して時刻を同期するようにクラスタを設定したり、保存データの暗号化を有効にしたりできます。

.開始する前に
次の情報を収集します。

* クラスタ管理 IP アドレス
+
クラスタ管理IPアドレスは、クラスタ管理インターフェイスの一意のIPv4アドレスです。クラスタ管理者は、管理Storage VMへのアクセスとクラスタの管理に使用します。このIPアドレスは、組織でIPアドレスを割り当てる管理者から取得できます。

* ネットワークサブネットマスク
+
ONTAPでは、クラスタのセットアップ時に、ご使用の構成に適した一連のネットワークインターフェイスを推奨します。必要に応じて推奨構成を調整できます。

* ネットワークゲートウェイのIPアドレス
* パートナーノードのIPアドレス
* DNSドメイン名
* DNSネームサーバのIPアドレス
* NTPサーバのIPアドレス
* データサブネットマスク


.手順
. クラスタネットワークを検出する
+
.. ラップトップを管理スイッチに接続し、ネットワークコンピュータとデバイスにアクセスします。
.. エクスプローラを開きます。
.. [ネットワーク]*を選択し、右クリックして*[更新]*を選択します。
.. いずれかのONTAPアイコンを選択し、画面に表示された証明書を受け入れます。
+
System Manager が開きます。



. [パスワード]*で、管理者アカウント用の強力なパスワードを作成します。
+
パスワードは8文字以上で、アルファベットと数字をそれぞれ1文字以上含む必要があります。

. 確認のためにパスワードを再入力し、*[続行]*を選択します。
. [ネットワークアドレス]*で、ストレージシステム名を入力するか、デフォルトの名前をそのまま使用します。
+
デフォルトのストレージシステム名を変更する場合は、新しい名前の1文字目はアルファベットで、44文字未満にする必要があります。名前にはピリオド（.）、ハイフン（-）、アンダースコア（_）を使用できます。

. クラスタ管理IPアドレス、サブネットマスク、ゲートウェイIPアドレス、およびパートナーノードのIPアドレスを入力し、*[続行]*を選択します。
. [ネットワークサービス]*で、*ホスト名の解決にドメインネームシステム（DNS）を使用する*と*時刻の同期を維持するためにネットワークタイムプロトコル（NTP）を使用する*のオプションを選択します。
+
DNSを使用する場合は、DNSドメインとネームサーバを入力します。NTPを使用する場合は、NTPサーバを入力して*[続行]*を選択します。

. [暗号化]*で、オンボードキーマネージャ（OKM）のパスフレーズを入力します。
+
デフォルトでは、オンボードキーマネージャ（OKM）を使用した保存データの暗号化が選択されています。外部キー管理ツールを使用する場合は、選択内容を更新します。

+
必要に応じて、クラスタのセットアップの完了後にクラスタで暗号化を設定できます。

. [初期化]*を選択します。
+
セットアップが完了すると、クラスタの管理IPアドレスにリダイレクトされます。

. [ネットワーク]*で、*[プロトコルの設定]*を選択します。
+
[cols="2"]
|===
| IP（iSCSIおよびNVMe/TCP）を設定する手順 | FCおよびNVMe/FCを設定する手順 


 a| 
.. [IP]*を選択し、*[IPインターフェイスの設定]*を選択します。
.. [サブネットの追加]*を選択します。
.. サブネットの名前を入力してから、サブネットのIPアドレスを入力します。
.. サブネットマスクを入力し、必要に応じてゲートウェイを入力して、*[追加]*を選択します。
.. 作成したサブネットを選択し、*[保存]*を選択します。
.. [ 保存（ Save ） ] を選択します。

 a| 
.. [FC]*を選択し、*[FCインターフェイスの設定]*および/または*[NVMe/FCインターフェイスの設定]*を選択します。
.. FCポート/ NVMe/FCポートを選択し、*[保存]*を選択します。


|===
. 必要に応じて、をダウンロードしてを実行し、link:https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ActiveIQ Config Advisor"]設定を確認します。
+
ActiveIQ Config Advisorは、一般的な構成エラーをチェックするNetAppシステム向けのツールです。



.次の手順
これで、link:set-up-data-access.html["データアクセスのセットアップ"]SANクライアントからASA R2システムに移行する準備が整いました。
