---
sidebar: sidebar 
permalink: install-setup/set-up-data-access.html 
keywords:  
summary:  
---
= SANホストからASA R2ストレージシステムへのデータアクセスを有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データアクセスをセットアップするには、ONTAPで適切に動作するためのSANクライアントの重要なパラメータと設定が正しく設定されていることを確認する必要があります。VMware環境用のストレージを提供する場合は、OTV 10.3をインストールしてASA R2ストレージを管理する必要があります。



== SANホストからのデータアクセスを設定する

SANホストからASA R2システムへのデータアクセスを設定するために必要な設定は、ホストのオペレーティングシステムとプロトコルによって異なります。最適なパフォーマンスと正常なフェイルオーバーを実現するには、正しい設定が重要です。

link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["VMware vSphere SCSIクライアント"^]link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["VMware vSphere NVMeクライアント"^]link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html["その他のSANクライアント"^]ASA R2システムに接続するようにホストを適切に設定するには、ONTAP SANホストのマニュアルを参照してください。



== VMware仮想マシンの移行

VMワークロードをASAストレージシステムからASA r2ストレージシステムに移行する必要がある場合、 NetApp以下を使用することを推奨しています。link:https://www.vmware.com/products/cloud-infrastructure/vsphere-foundation["VMware vSphere vMotion"^]中断なくライブでデータの移行を実行します。

.関連情報
* 詳細はこちらlink:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-why.html["ONTAP for vSphere を使用する利点"^] 。
* 学ぶlink:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-srm-overview.html["ONTAPを使用した VMware ライブ サイト リカバリ"^]。
* 学ぶlink:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html#continuous-availability-solutions-for-vsphere-environments["vSphere環境向けの継続的な可用性ソリューション"^]。




== サードパーティのストレージシステムからデータを移行する

ONTAP 9.17.1以降では、Foreign LUN Import（FLI）を使用して、サードパーティ製ストレージシステムのLUNからASA r2システムにデータを移行できます。データ移行にFLIを使用すると、移行プロセス中のデータ損失やダウンタイムのリスクを軽減できます。

FLIはオンラインとオフラインの両方の移行をサポートしています。オンライン移行では、サードパーティ製ストレージシステムからONTAPストレージシステムへのデータのコピー中も、クライアントシステムはオンラインのままです。オンライン移行は、Windows、Linux、ESXiホストオペレーティングシステムでサポートされています。オフライン移行では、クライアントシステムがオフラインになり、LUNデータがサードパーティ製ストレージシステムからONTAPストレージシステムにコピーされた後、クライアントシステムがオンラインに戻ります。

* 実行方法を学ぶlink:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_offline_workflow.html["FLIオフライン移行"^] 。
* 実行方法を学ぶlink:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_online_workflow.html["FLIオンライン移行"^] 。




== ASA R2システムをVMware環境のストレージプロバイダとして設定する

ONTAP tools for VMwareを使用すると、ASA R2システムをVMware環境のストレージプロバイダとして簡単に有効にすることができます。

ONTAP Tools for VMware vSphereは、VMware vCenter Server Virtual Appliance（vCSA）と連携して動作する一連のツールで、VMware ESXiホスト上の仮想マシンを簡単に管理できます。

ASA R2システムは、以降でサポートされlink:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-overview.html["ONTAP tools for VMware vSphere 10.3"^]ます。

その方法を説明しlink:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["ONTAP Tools for VMwareの導入"^]、次の操作を実行します。

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["vCenter Serverインスタンスの追加"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-esx-server-multipath-and-timeout-settings.html["ESXiホストの設定"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/discover-storage-systems-and-hosts.html["ASA R2ストレージシステムとホストの検出"^]


.次の手順
これで、link:../manage-data/provision-san-storage.html["ストレージのプロビジョニング"]SANホストがストレージユニットに対してデータの読み取りと書き込みを実行できるようになります。
