---
sidebar: sidebar 
permalink: secure-data/migrate-encryption-keys-between-key-managers.html 
keywords: onboard key manager, external key manager, configure, migrate keys, store keys, authentication keys, encryption keys, asa r2 
summary: データ暗号化キーは、ASA R2システム上のONTAPオンボードキーマネージャ、外部キーマネージャ、またはその両方（一方の場合）で管理できます。 
---
= ASA R2システムのキー管理ツール間でONTAPデータ暗号化キーを移行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ暗号化キーは、ASA R2システムのONTAPオンボードキーマネージャまたは外部キー管理ツール（またはその両方）を使用して管理できます。外部キー管理ツールはStorage VMレベルでのみ有効にできます。ONTAPクラスタレベルでは、オンボードキーマネージャまたは外部キーマネージャを有効にできます。

[cols="2,2"]
|===
| キー管理ツールを有効にする場所 | 使用できる機能 


| クラスタレベルのみ  a| 
オンボードキーマネージャまたは外部キー管理ツール



| ストレージVMレベルのみ | 外部キー管理ツールのみ 


 a| 
クラスタとストレージVMレベルの両方
 a| 
次のいずれかのキー管理ツールの組み合わせ：

* オプション1
+
クラスタレベル：オンボードキーマネージャ

+
ストレージVMレベル: 外部キーマネージャー

* オプション2
+
クラスタレベル：外部キー管理ツール

+
ストレージVMレベル: 外部キーマネージャー



|===


== ONTAPクラスタレベルでのキー管理ツール間でのキーの移行

ONTAP 9.16.1以降では、ONTAPのコマンドラインインターフェイス（CLI）を使用して、クラスタレベルのキー管理ツール間でキーを移行できます。

[role="tabbed-block"]
====
.オンホオトカラカイフヘ
--
.手順
. 権限レベルをadvancedに設定します。
+
[source, cli]
----
set -privilege advanced
----
. 非アクティブな外部キー管理ツールの設定を作成します。
+
[source, cli]
----
security key-manager external create-config
----
. 外部キー管理ツールに切り替えます。
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type KMIP
----
. オンボードキーマネージャの設定を削除します。
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type OKM
----
. 権限レベルをadminに設定します。
+
[source, cli]
----
set -privilege admin
----


--
.カイフカラオンボードヘ
--
.手順
. 権限レベルをadvancedに設定します。
+
[source, cli]
----
set -privilege advanced
----
. 非アクティブなオンボードキーマネージャの設定を作成します。
+
[source, cli]
----
security key-manager onboard create-config
----
. オンボードキーマネージャの設定を有効にします。
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type OKM
----
. 外部キー管理ツールの設定を削除します。
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type KMIP
----
. 権限レベルをadminに設定します。
+
[source, cli]
----
set -privilege admin
----


--
====


== ONTAPクラスタレベルとStorage VMレベルのキー管理ツール間でキーを移行

ONTAPのコマンドラインインターフェイス（CLI）を使用して、クラスタレベルのキー管理ツールとStorage VMレベルのキー管理ツールの間でキーを移行できます。

.手順
. 権限レベルをadvancedに設定します。
+
[source, cli]
----
set -privilege advanced
----
. キーを移行します。
+
[source, cli]
----
security key-manager key migrate -from-vserver <storage_vm_name> -to-vserver <storage_vm_name>
----
. 権限レベルをadminに設定します。
+
[source, cli]
----
set -privilege admin
----

