---
sidebar: sidebar 
permalink: secure-data/pause-resume-anti-ransomware-protection.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, pause, resume, suspend 
summary: 異常なワークロードイベントを計画している場合は、ランサムウェア攻撃の誤検出を防ぐために、AI分析を使用したARPを一時的に停止できます 
---
= ASA r2ストレージシステムでARP/AI保護を一時停止または再開する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.17.1以降、Autonomous Ransomware Protection with Artificial Intelligence（ARP/AI）を使用して、ASA r2システム上のデータを保護できます。通常とは異なるワークロードイベントが予定されている場合は、誤検知を防ぐためにARP/AI分析を一時的に停止することができます。イベントが終了したら、ARP/AI分析を再開できます。



[[pause-arpai]]
== ARP/AIを一時停止

通常とは異なるワークロードイベントを開始する前に、誤検知を防ぐためにARP/AI分析を一時的に停止する必要がある場合があります。

.手順
. System Managerで、*[ストレージ]*を選択します。
. ARP/AI を一時停止するストレージ ユニットを選択します。
. *ランサムウェア対策を一時停止*を選択します。


.結果
選択したストレージ ユニットの ARP/AI 分析は一時停止され、ARP/AI を再開するまで System Manager で疑わしいアクティビティは報告されません。



[[resume-arpai]]
== ARP/AIを再開する

通常とは異なるワークロードが発生した際にARP/AIを一時停止した場合は、ワークロードが完了した後に再開して、ランサムウェア攻撃からデータを保護してください。

.手順
. System Managerで、*[ストレージ]*を選択します。
. ARP/AI を再開するストレージ ユニットを選択します。
. *ランサムウェア対策を再開*を選択します。


.結果
潜在的なランサムウェア攻撃の分析が再開され、疑わしいアクティビティが System Manager に報告されます。
