---
sidebar: sidebar 
permalink: secure-data/respond-anti-ransomware-protection-alerts.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, arp/ai, alerts, respond, warnings, security 
summary: 潜在的なランサムウェア攻撃の警告を表示し、System Manager でアクションを実行します。 
---
= ASA r2 ストレージ システムの AI アラートによる自律的なランサムウェア防御に対応
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
人工知能（ARP/AI）を活用した自律ランサムウェア保護機能が、 ASA r2システムのストレージユニット1台以上で異常なアクティビティを検知した場合、System Managerダッシュボードに警告が表示されます。警告を確認し、アクティビティを確認し、必要に応じてデータへの潜在的な脅威を阻止するための措置を講じてください。

ARP/AI警告メッセージが表示された場合は、対処する前に、適切なアプリケーション整合性チェッカーを使用して、ストレージユニット上のデータの整合性を確認してください。ストレージユニットのデータ整合性を確認することで、アクティビティが許容できるものなのか、それともランサムウェア攻撃の可能性があるものなのかを判断するのに役立ちます。

[cols="2,2"]
|===
| 異常な活動が... | 操作 


| 許容できる | アクティビティを誤検知としてマークします。 


| 潜在的なランサムウェア攻撃 | アクティビティを潜在的なランサムウェア攻撃としてマークします。 


| 不確定 | すぐに行動を起こさないでください。ストレージユニットを最大7日間監視してください。ストレージユニットが正常に動作し続ける場合は、そのアクティビティを誤検知としてマークしてください。ストレージユニットが異常なアクティビティを示し続ける場合は、そのアクティビティをランサムウェア攻撃の可能性としてマークしてください。 
|===
.手順
. System Manager で、 * Dashboard * を選択します。
+
ARP が 1 つ以上のストレージ ユニットで異常なアクティビティを検出した場合、[*警告*] の下にメッセージが表示されます。

. 警告メッセージを選択します。
. *イベントの概要*で、異常なアクティビティが発生しているストレージ ユニットの数を示す *警告* メッセージを選択します。
. *異常なアクティビティが発生しているストレージ ユニット* の下で、ストレージ ユニットを選択します。
. *セキュリティ*を選択します。
+
ストレージ ユニットで異常なアクティビティが発生した場合は、[*ランサムウェア対策*] の下にメッセージが表示されます。

. *アクションを選択*を選択します。
. *誤検知としてマーク*を選択するか、*潜在的なランサムウェア攻撃としてマーク*を選択します。

