---
sidebar: sidebar 
permalink: secure-data/respond-anti-ransomware-protection-alerts.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, alerts, respond, warnings, security 
summary: 潜在的なランサムウェア攻撃の警告を表示し、System Manager でアクションを実行します。 
---
= ASA r2ストレージシステムでのARP/AIアラートへの対応
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Autonomous Ransomware Protection with Artificial Intelligence（ARP/AI）が、ASA r2システムの1つまたは複数のストレージユニットで異常なアクティビティを検出した場合、System Managerはダッシュボードに警告を表示します。警告内容を確認し、アクティビティを検証し、必要に応じてデータを保護するための措置を講じてください。

ARP/AI警告メッセージが表示された場合は、適切なアプリケーション整合性チェッカーを使用して、ストレージユニット上のデータを検証してから対処してください。ストレージユニットのデータ整合性を検証することで、そのアクティビティが許容範囲内のものか、あるいはランサムウェア攻撃の可能性があるかを判断できます。

[cols="2,2"]
|===
| 異常な活動が... | 操作 


| 許容できる | アクティビティを誤検知としてマークします。 


| 潜在的なランサムウェア攻撃 | アクティビティを潜在的なランサムウェア攻撃としてマークします。 


| 不確定 | 直ちに行動を起こさないでください。ストレージユニットを最大7日間監視します。ストレージユニットが正常に動作し続ける場合は、そのアクティビティを誤検知としてマークしてください。ストレージユニットが異常なアクティビティを継続的に示す場合は、そのアクティビティをランサムウェア攻撃の可能性としてマークしてください。 
|===
.手順
. System Manager で、 * Dashboard * を選択します。
+
ARP/AIが1つ以上のストレージユニットで異常なアクティビティを検出した場合、*警告*の下にメッセージが表示されます。

. 警告メッセージを選択します。
. *イベントの概要*で、異常なアクティビティが発生しているストレージ ユニットの数を示す *警告* メッセージを選択します。
. *異常なアクティビティが発生しているストレージ ユニット* の下で、ストレージ ユニットを選択します。
. *セキュリティ*を選択します。
+
ストレージ ユニットで異常なアクティビティが発生した場合は、[*ランサムウェア対策*] の下にメッセージが表示されます。

. *アクションを選択*を選択します。
. *誤検知としてマーク*を選択するか、*潜在的なランサムウェア攻撃としてマーク*を選択します。


.次の手順
ストレージユニットのアクティビティに急増が見られる場合（一時的な急増、または新たな常態を特徴づける急増のいずれか）は、それらを安全として報告する必要があります。これらの急増を手動で安全として報告することで、ARPの脅威評価の精度向上に役立ちます。link:https://docs.netapp.com/us-en/ontap/anti-ransomware/manage-parameters-task.html#report-known-surges["既知のARP/AIサージを報告する"^]の方法を確認してください。
