---
settings:
  name: ASA r2
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: ASA R2のドキュメント
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: manage-data
  - section: administer
  - title: ハードウェアのメンテナンス
    url: "/maintain-hardware.html"
  - section: learn-more
  - section: get-help
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
