---
sidebar: sidebar 
permalink: learn-more/hardware-comparison.html 
keywords: compare asa r2, asa a1k, asa a90, asa a70 
summary: ASAシステムは、SANのみのソリューション向けに最適化されたハードウェアサポートを提供します。ASA R2システムは、ハードウェアとソフトウェアの最適化を提供します。 
searchtitle: ASA R2システムを他のONTAPシステムと比較する 
---
= ASA R2システムを他のONTAPシステムと比較する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA R2システムは、オールフラッシュプラットフォーム上に構築されたSAN専用環境向けに、ハードウェアとソフトウェアの統合ソリューションを提供します。ASA R2システムのストレージレイヤ、サポートされるプロトコル、ONTAPパーソナリティの実装において、他のONTAPシステム（ASA、AFF、FAS）とは異なります。

ASA R2システムでは、ONTAPソフトウェアが合理化され、SAN関連以外の機能の可視性と可用性を制限しながら、重要なSAN機能をサポートします。たとえば、ASA R2システムで実行されているSystem Managerには、NASクライアントのホームディレクトリを作成するオプションは表示されません。この合理化されたバージョンのONTAPは、_ ASA R2 personality_として識別されます。他のすべてのONTAPシステム（ASA、AFF、FAS）で実行されているONTAPは、_Unified ONTAP personality_として識別されます。ONTAPのパーソナリティの違いについては、ONTAPコマンドリファレンス（マニュアルページ）、REST API仕様、およびEMSメッセージ（該当する場合）を参照してください。

ONTAPストレージのパーソナリティは、System ManagerまたはONTAP CLIを使用して確認できます。

* System Managerのメニューで、*[クラスタ]>[概要]*を選択します。
* CLIから、次のように入力します。 `san config show`


ONTAPストレージシステムのパーソナリティは変更できません。

Unified ONTAPパーソナリティを実行するONTAPシステムのストレージレイヤでは、ストレージのベースユニットとしてアグリゲートが使用されます。アグリゲートは、ストレージシステムで使用可能な特定のディスクセットを所有します。アグリゲートは、自身が所有するディスクのスペースをLUNおよびネームスペース用のボリュームに割り当てます。Unified ONTAPユーザは、コマンドラインインターフェイス（CLI）を使用して、アグリゲート、ボリューム、LUN、ネームスペースを作成および変更できます。

ASA R2システムのストレージレイヤでは、アグリゲートではなくストレージアベイラビリティゾーンを使用します。ストレージアベイラビリティゾーンは、ストレージシステム内の使用可能なすべてのディスクにアクセスできる共通のストレージプールです。ストレージアベイラビリティゾーンは、ASA R2 HAペアの両方のノードから認識できます。ストレージユニット（LUNまたはNVMeネームスペースに基づく）を作成すると、そのストレージユニットを格納するStorage Virtual Machine（VM）を含むボリュームがONTAPのストレージアベイラビリティゾーンに自動的に作成されます。この自動化されたシンプルなストレージ管理アプローチにより、ASA R2システムでは、特定のSystem Managerオプション、ONTAPコマンド、およびREST APIエンドポイントを使用できないか、または使用方法が制限されています。たとえば、ボリュームの作成と管理はASA R2システムで自動化されているため、*[ボリューム]*メニューはSystem Managerに表示されず、 `volume create`コマンドはサポートされません。

ASA R2ストレージは、次の点で他のONTAPストレージシステムと比較されます。

[cols="1h,2,2,2,2"]
|===
|  | ASA r2 | ASA | AFF | FAS 


 a| 
* ONTAPパーソナリティ*
| ASA r2 | ASA | 統合 | 統合 


 a| 
* SANプロトコルのサポート*
| はい | はい | はい | はい 


 a| 
* NASプロトコルのサポート*
| いいえ | いいえ | はい | はい 


 a| 
*ストレージ・レイヤーのサポート*
| ストレエシアベイラビリティソオン | アグリゲート | アグリゲート | アグリゲート 
|===
次のASAプラットフォームは、ASA R2システムに分類されます。

* ASA A1K
* ASA A70
* ASA A90


.詳細情報
* 詳細については、をご覧ください link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["ONTAPハードウェアシステム"^]。
* のASAおよびASA R2システムの構成の完全なサポートと制限事項を参照してくださいlink:https://hwu.netapp.com/["NetApp Hardware Universe"^]。
* の詳細については、をlink:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^]参照してください。




== ASA R2システムの相違点のまとめ

ASA R2システムと、ONTAP CLI（コマンドラインインターフェイス）およびREST APIに関連するFAS、AFF、およびASAシステムの主な違いを次に示します。

.プロトコルサービスを使用したデフォルトのSVM作成
新しいクラスタには、SANプロトコルが有効になったデフォルトのデータSVMが自動的に含まれます。IPデータLIFは、iSCSIプロトコルとNVMe/TCPプロトコルをサポートし、 `default-data-blocks`デフォルトでサービスポリシーを使用します。

.自動ボリューム作成
ストレージユニット（LUNまたはネームスペース）を作成すると、ストレージのアベイラビリティゾーンからボリュームが自動的に作成されます。これにより、シンプルで共通のネームスペースが実現します。ストレージユニットを削除すると、関連付けられているボリュームも自動的に削除されます。

.シンプロビジョニングとシックプロビジョニングに対する変更
ストレージユニットは、常にASA R2ストレージシステム上でシンプロビジョニングされます。シックプロビジョニングはサポートされません。

.データ圧縮に対する変更
温度に基づくストレージ効率化は、ASA R2システムには適用されません。ASA R2システムでは、_hot_（アクセス頻度の高い）データや_cold_（アクセス頻度の低い）データには基づいて圧縮されません。圧縮は、データがコールドになるのを待たずに開始されます。
