---
sidebar: sidebar 
permalink: learn-more/hardware-comparison.html 
keywords: compare asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, hardware comparison, asa r2 
summary: ASAシステムは、SANのみのソリューション向けに最適化されたハードウェアサポートを提供します。ASA R2システムは、ハードウェアとソフトウェアの最適化を提供します。 
searchtitle: ASA R2システムを他のONTAPシステムと比較する 
---
= ASA R2システムを他のONTAPシステムと比較する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2 システムは、オールフラッシュ ソリューション上に構築された SAN のみの環境向けのハードウェアおよびソフトウェア ソリューションを提供します。ASAシステムは、 ONTAPパーソナリティ、ストレージ レイヤー、およびサポートされるプロトコルの実装において、他のONTAPシステム ( ASA 、 AFF、 FAS ) とは異なります。

以下はASA r2 システムとして分類されます。

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30




== 性格の違い

ASA R2システムでは、ONTAPソフトウェアが合理化され、SAN関連以外の機能の可視性と可用性を制限しながら、重要なSAN機能をサポートします。たとえば、ASA R2システムで実行されているSystem Managerには、NASクライアントのホームディレクトリを作成するオプションは表示されません。この合理化されたバージョンのONTAPは、_ ASA R2 personality_として識別されます。ASAシステムで実行されているONTAPは、_ ASA ONTAP personality_として識別されます。AFFおよびFAS ONTAPシステムで実行されているONTAPは、_Unified ONTAP personality_として識別されます。ONTAPのパーソナリティの違いについては、ONTAPコマンドリファレンス（マニュアルページ）、REST API仕様、およびEMSメッセージ（該当する場合）を参照してください。

ONTAPストレージのパーソナリティは、System ManagerまたはONTAP CLIを使用して確認できます。

* System Managerのメニューで、*[クラスタ]>[概要]*を選択します。
* CLI から次のように入力します。 `system node show -personality -is-disaggregated`


ASA r2 システムの場合、_personality_ は _ASA r2_ であり、_is-disaggregated_ のステータスは _true_ です。

ONTAPストレージシステムのパーソナリティは変更できません。



== ストレージ層の違い

ASA r2 システムは、 FAS、 AFF、およびASAシステムで使用されるストレージ レイヤーとは異なる、簡素化されたストレージ レイヤーを使用します。

.FAS、 AFF、 ASAシステム
FAS、 AFF、 ASAシステムのストレージレイヤーでは、ストレージの基本単位としてアグリゲートを使用します。アグリゲートは、ストレージシステムで利用可能な特定のディスクセットを所有します。アグリゲートは、所有するディスク上のスペースを、LUNおよびネームスペース用のボリュームに割り当てます。これらのシステムでは、 ONTAPユーザーはアグリゲート、ボリューム、LUN、ネームスペースを作成および変更できます。

.ASA r2システム
ASA r2 システムのストレージ層では、アグリゲートの代わりにストレージ アベイラビリティ ゾーンが使用されます。ストレージ アベイラビリティ ゾーンとは、単一の HA ペアの両方のノードで利用可能な共通のストレージ プールです。HAペアの両方のノードは、共有ストレージ アベイラビリティ ゾーン内のすべての利用可能なディスクにアクセスできます。たとえば、2 ノードのASA r2 システムONTAPクラスタには、クラスタ内の両方のノードからアクセスできる 1 つのストレージ アベイラビリティ ゾーンがあります。4ノードのASA r2 システムONTAPクラスタには、2 つのストレージ アベイラビリティ ゾーンがあります。クラスタ内の各 HA ペアは、いずれかのストレージ アベイラビリティ ゾーンにアクセスできます。

ストレージユニット（LUNまたはNVMeネームスペースベース）が作成されると、 ONTAPは適切なストレージアベイラビリティゾーンにストレージユニットを格納するボリュームを自動的に作成します。新しく作成されたボリュームは、最適なパフォーマンスとバランスの取れた容量利用率を実現するために、ストレージアベイラビリティゾーン内に自動的に配置されます。ONTAPのONTAPに応じて、 ASA r2システムは、ストレージアベイラビリティゾーン全体にわたるストレージユニットの自動リバランスと、HAペアのノード間のワークロードの自動リバランスもサポートします。

* 自動ストレージユニットの再バランス調整
+
ONTAP 9.16.1 以降、ストレージ ユニットが増加または減少してストレージ可用性ゾーン全体でストレージ使用率の不均衡が生じた場合、 ONTAP は必要に応じてストレージ ユニットを自動的に移動し、使用率を再調整してパフォーマンスを最適化します。

* 自動ワークロード再調整
+
ONTAP 9.17.1以降、 ONTAPはASA r2システムのHAペア内のノード間でワークロードを自動的に再調整し、最適なパフォーマンスを実現します。例えば、一方のノードの使用率が70%に上昇したのに対し、そのHAペアのノードの使用率が30%にとどまっている場合、 ONTAPは各ノードの使用率がより均等になるようにワークロードを自動的にシフトします。HAペアのノードは同じストレージアベイラビリティゾーンを共有しているため、ワークロードの再調整はコピーフリーの操作であり、パフォーマンスに影響を与えません。ワークロード再調整は、 ONTAP 9.17.1へのアップグレード後、または新しいONTAP 9.17.1 ASA r2クラスタの初期化後14日でデフォルトで有効になります。link:../administer/rebalance-workloads.html["デフォルト設定を変更する"]自動ワークロード再バランスを有効または無効にしたり、不均衡なワークロードを自動的に移動せずにフラグを立てるアドバイス状態に設定したりします。





== ASA R2システムの相違点のまとめ

ASA r2 システムは、 FAS、 AFF、およびASAシステムと次の点で異なります。

[cols="1h,2,2,2,2"]
|===
|  | ASA r2 | ASA | AFF | FAS 


 a| 
* ONTAPパーソナリティ*
| ASA r2 | ASA | 統合 | 統合 


 a| 
* SANプロトコルのサポート*
| はい | はい | はい | はい 


 a| 
* NASプロトコルのサポート*
| いいえ | いいえ | はい | はい 


 a| 
*ストレージ・レイヤーのサポート*
| ストレエシアベイラビリティソオン | アグリゲート | アグリゲート | アグリゲート 
|===
ストレージ管理に対するこの自動化され簡素化されたアプローチのため、System Managerの一部のオプション、 ONTAPコマンド、およびREST APIエンドポイントはASA r2システムでは利用できないか、使用が制限されています。例えば、 ASA r2システムではボリュームの作成と管理が自動化されているため、System Managerに「ボリューム」メニューが表示されず、  `volume create`コマンドはサポートされていません。link:cli-support.html["サポートされていないASA r2 コマンドの詳細"] 。

ASA R2システムと、ONTAP CLI（コマンドラインインターフェイス）およびREST APIに関連するFAS、AFF、およびASAシステムの主な違いを次に示します。

.プロトコル サービスを使用したデフォルトのストレージ VM の作成
新しいクラスターには、SAN プロトコルが有効になっているデフォルトのデータ ストレージ仮想マシン (VM) が自動的に含まれます。  IPデータLIFはiSCSIおよびNVMe/TCPプロトコルをサポートし、 `default-data-blocks`デフォルトのサービス ポリシー。

.自動ボリューム作成
ストレージユニット（LUNまたはネームスペース）を作成すると、ストレージのアベイラビリティゾーンからボリュームが自動的に作成されます。これにより、シンプルで共通のネームスペースが実現します。ストレージユニットを削除すると、関連付けられているボリュームも自動的に削除されます。

.シンプロビジョニングとシックプロビジョニングに対する変更
ストレージユニットは、常にASA R2ストレージシステム上でシンプロビジョニングされます。シックプロビジョニングはサポートされません。

.データ圧縮に対する変更
温度に基づくストレージ効率化は、ASA R2システムには適用されません。ASA R2システムでは、_hot_（アクセス頻度の高い）データや_cold_（アクセス頻度の低い）データには基づいて圧縮されません。圧縮は、データがコールドになるのを待たずに開始されます。

.詳細情報
* 詳細については、をご覧ください link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["ONTAPハードウェアシステム"^]。
* のASAおよびASA R2システムの構成の完全なサポートと制限事項を参照してくださいlink:https://hwu.netapp.com/["NetApp Hardware Universe"^]。
* の詳細については、をlink:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^]参照してください。

