---
sidebar: sidebar 
permalink: learn-more/software-support-limitations.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, asa c30, unsupported features 
summary: ASA R2システムはSANソリューションを幅広くサポートしていますが、一部のONTAPソフトウェア機能はサポートされていません。 
---
= ASA R2ストレージシステムのONTAPソフトウェアのサポートおよび制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2システムは幅広いSAN機能をサポートしていますが、一部のONTAPソフトウェア機能はサポートされていません。

.ASA R2システムでは、次の機能はサポートされません。
* FabricPool
* LUNシックプロビジョニング
* MetroCluster
* NetApp Aggregate Encryption（NAE）
* オブジェクトプロトコル
* ONTAP S3 SnapMirrorとS3 API
* SnapLock
+
SnapLock Compliance および Enterprise モードは、SAN 環境のプライマリクラスタではサポートされていません。SnapLock for SnapVault はセカンダリ システムのクラスタでサポートされています。

* SnapMirrorレプリケーションは、次の制限付きでASA r2 システムでサポートされます。
+
** SnapMirror同期レプリケーションはサポートされていません。
** SnapMirror の非同期レプリケーションは、2つの ASA r2 システム間でのみサポートされます。SnapMirror の非同期レプリケーションは、ASA r2 システムと ASA、AFF、または FAS システム間、あるいはクラウドとの間ではサポートされていません。
+
詳細はこちらlink:../data-protection/pre-defined-protection-policies.html["ASA r2 システムでサポートされるSnapMirrorレプリケーション ポリシー"]。

** SnapMirrorアクティブ同期は、2 つのASA r2 システム間でのみサポートされます。
+
詳細はこちらlink:../data-protection/snapmirror-active-sync.html["ASA r2 システムでのSnapMirrorアクティブ同期"]。





.ASA R2システムは、次の機能をサポートしています。
* デュアルレイヤ暗号化
+
ASA r2システムは、自己暗号化ドライブ（SED）を使用したハードウェア暗号化と、NetApp Volume Encryption（NVE）テクノロジーを使用したソフトウェア暗号化をサポートしています。link:../secure-data/encrypt-data-at-rest.html["デュアルレイヤ暗号化の適用方法"]ASA r2システム上のデータに。



.詳細情報
* link:https://hwu.netapp.com/["NetApp Hardware Universe"^]ASA R2ハードウェアのサポートおよび制限事項の詳細については、を参照してください。

