---
sidebar: sidebar 
permalink: manage-data/migrate-svm.html 
keywords: move svm, migrate svm, asa, asa r2, storage vm, storage virtual machine 
summary: ストレージ可用性ゾーンのスペースが少なくなってきた場合は、ストレージユニットを別のストレージ可用性ゾーンに移動して、クラスタ全体でストレージ利用率を分散させることができます。 
---
= ストレージVMをASAクラスタからASA r2クラスタに移行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.18.1 以降では、任意のASAクラスタから任意のASA r2 クラスタにストレージ仮想マシン (VM) を無停止で移行できます。  ASAクラスタからASA r2 クラスタに移行すると、SAN のみの環境向けにASA r2 システムの簡素化され合理化されたアーキテクチャを採用できます。

ASAとASA r2 ストレージ システム間のストレージ VM 移行は、次のようにサポートされます。

[cols="2"]
|===
| 以下のいずれかのASAシステムから: | 以下のいずれかのASA r2 システム: 


 a| 
* ASA C800
* ASA C400
* ASA C250
* ASA A900
* ASA A800
* ASA A400
* ASA A250
* ASA A150
* ASA AFF A800
* ASA AFF A700
* ASA AFF A400
* ASA AFF A250
* ASA AFF A220

 a| 
* ASA A1K
* ASA C30
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20


|===

NOTE: ASAおよびASA r2システムの最新のリストについては、以下を参照してください。link:https://hwu.netapp.com/["NetApp Hardware Universe"^] 。  ASA r2 システムは、 NetApp Hardware Universeに「ASA A シリーズ/C シリーズ (新規)」として記載されています。

ストレージ VM を ASA クラスタからASA r2 クラスタに移行できるのは、 ASAクラスタからのみです。他のタイプのONTAPシステムからの移行はサポートされていません。

.開始する前に
ASA r2 クラスタとASAクラスタ内のすべてのノードでONTAP 9.18.1 以降が実行されている必要があります。クラスタ ノード上のONTAP 9.18.1 パッチ バージョンは異なる場合があります。



== ステップ1: ASAストレージVMのステータスを確認する

ASAシステムからストレージ VM を移行する前に、NVMe 名前空間またはvVols が存在しないようにし、ストレージ VM 内の各ボリュームに LUN が 1 つだけ含まれている必要があります。  NVMe 名前空間とvVolsの移行はサポートされていません。  ASA r2 システムのアーキテクチャでは、ボリュームに単一の LUN が含まれている必要があります。

.手順
. ストレージ VM に NVMe 名前空間が存在しないことを確認します。
+
[source, cli]
----
vserver nvme namespace show -vserver <storage_VM>
----
+
エントリが表示されている場合は、NVMeオブジェクトはlink:https://docs.netapp.com/us-en/ontap/nvme/convert-namespace-to-lun-task.html["変換された"^]LUN に追加または削除します。参照 `vserver nvme namespace delete`そして `vserver nvme subsystem delete`コマンドlink:https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html["ONTAPコマンド リファレンス"^]詳細についてはこちらをご覧ください。

. ストレージ VM にvVolsが存在しないことを確認します。
+
[source, cli]
----
lun show -verser <storage_VM> -class protocol-endpoint,vvol
----
+
vVolsが存在する場合は、それらを別のストレージ VM にコピーし、移行するストレージ VM から削除する必要があります。参照 `lun copy`そして `lun delete`コマンドlink:https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html["ONTAPコマンド リファレンス"^]詳細についてはこちらをご覧ください。

. ストレージ VM 内の各ボリュームに単一の LUN が含まれていることを確認します。
+
[source, cli]
----
lun show -verser <storage_VM>
----
+
ボリュームに複数のLUNが含まれている場合は、 `volume create`そして `lun move`1:1 のボリュームと LUN の比率を作成するコマンド。詳細については、link:https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html["ONTAPコマンド リファレンス"^]を参照してください。



.次の手順
ASAとASA r2 クラスタ間のクラスタ ピア関係を作成する準備が整いました。



== ステップ2: ASAとASA r2クラスタ間のクラスタピア関係を作成する

ストレージ VM をASAクラスタからASA r2 クラスタに移行する前に、ピア関係を作成する必要があります。ピア関係は、 ONTAPクラスタとストレージ VM が安全にデータを交換できるようにするネットワーク接続を定義します。

.開始する前に
次のいずれかの方法を使用して、ピアリングするクラスタ内のすべてのノードにクラスタ間 LIF を作成する必要があります。

* link:https://docs.netapp.com/us-en/ontap/peering/configure-intercluster-lifs-share-data-ports-task.html["共有データ ポートでのクラスタ間LIFの設定"^]
* link:https://docs.netapp.com/us-en/ontap/peering/configure-intercluster-lifs-use-dedicated-ports-task.html["専用データ ポートでのクラスタ間LIFの設定"^]
* link:https://docs.netapp.com/us-en/ontap/peering/configure-intercluster-lifs-use-ports-own-networks-task.html["カスタムIPspaceでのクラスタ間LIFの設定"^]


.手順
. ASA r2 クラスタで、 ASAクラスタとのピア関係を作成し、パスフレーズを生成します。
+
[source, cli]
----
cluster peer create -peer-addrs <ASA_cluster_LIF_IPs> -generate-passphrase
----
+
次の例では、クラスタ 1 とクラスタ 2 の間にクラスタ ピア関係を作成し、システム生成のパスフレーズを作成します。

+
[listing]
----
cluster1::> cluster peer create -peer-addrs 10.98.191.193 -generate-passphrase
Passphrase: UCa+6lRVICXeL/gq1WrK7ShR
            Peer Cluster Name: cluster2
            Initial Allowed Vserver Peers: -
            Expiration Time: 6/7/2017 09:16:10 +5:30
            Intercluster LIF IP: 10.140.106.185
Warning: make a note of the passphrase - it cannot be displayed again.

----
. 生成されたパスフレーズをコピーします。
. ASAクラスタで、 ASA r2 クラスタとのピア関係を作成します。
+
[source, cli]
----
cluster peer create -peer-addrs <ASA_r2_LIF_IPs>
----
. ASA r2 クラスタで生成されたパスフレーズを入力します。
. クラスター ピア関係が作成されたことを確認します。
+
[source, cli]
----
cluster peer show
----
+
次の例は、正常にピアリングされたクラスターの予想される出力を示しています。

+
[listing]
----
cluster1::> cluster peer show

Peer Cluster Name   Cluster Serial Number   Availability   Authentication
-----------------   ---------------------   -------------- --------------
cluster2             1-80-123456             Available      ok
----


.結果
ASAクラスタとASA r2 クラスタはピアリングされており、ストレージ VM データを安全に転送できます。

.次の手順
ASAストレージ VM を移行用に準備する準備が整いました。



== ステップ3: ASAからASA r2クラスタへのストレージVMの移行の準備

ストレージ仮想マシン (VM) をASAクラスタからASA r2 クラスタに移行する前に、移行の事前チェックを実行し、必要な問題を修正する必要があります。事前チェックが正常に完了するまで、移行を実行することはできません。

.ステップ
. ASA r2 クラスタから、移行事前チェックを実行します。
+
[source, cli]
----
vserver migrate start -vserver <storage_VM> -source-cluster <asa_cluster> -check-only true
----
+
ASAクラスタを移行する準備をするために問題を修正する必要がある場合は、問題と修正アクションが表示されます。問題を修正し、正常に完了するまで事前チェ​​ックを繰り返します。



.次の手順
ストレージ VM をASAクラスターからASA r2 クラスターに移行する準備が整いました。



== ステップ4: ASAストレージVMをASA r2クラスタに移行する

ASAクラスタを準備し、 ASA r2 クラスタとの必要なクラスタ ピア関係を作成したら、ストレージ VM の移行を開始できます。

ストレージ VM の移行を実行する場合は、CPU ワークロードを実行できるように、 ASAクラスタとASA r2 クラスタの両方で 30% の CPU ヘッドルームを残すことがベスト プラクティスです。

.タスクの内容
ストレージ VM の移行後、クライアントは自動的にASA r2 クラスタに切り替えられ、 ASAクラスタ上のストレージ VM は自動的に削除されます。自動カットオーバーと自動ストレージ VM 削除はデフォルトで有効になっています。必要に応じて、両方を無効にして、カットオーバーとストレージ VM の削除を手動で実行することもできます。

.開始する前に
* ASA r2 クラスタには、移行されたストレージ VM を保持するのに十分な空き領域が必要です。
* ASAストレージ VM に暗号化されたボリュームが含まれている場合は、 ASA r2 システム上のオンボード キー マネージャまたは外部キー マネージャをクラスタ レベルで設定する必要があります。
* 次の操作はソースASAクラスタでは実行できません。
+
** フェイルオーバー操作
** ワフリロン
** 指紋
** ボリュームの移動、再ホスト、クローン作成、作成、変換、分析




.手順
. ASA r2 クラスタから、ストレージ VM の移行を開始します。
+
[source, cli]
----
vserver migrate start -vserver <storage_VM_name> -source-cluster <ASA_cluster>
----
+
自動カットオーバーを無効にするには、 `-auto-cutover false`パラメータ。  ASAストレージVMの自動削除を無効にするには、 `-auto-source-cleanup false`パラメータ。

. 移行のステータスを監視する
+
[source, cli]
----
vserver migrate show -vserver <storage_VM_name>
----
+
移行が完了すると、*ステータス*が*移行完了*と表示されます。




NOTE: 自動カットオーバーが始まる前に移行を一時停止またはキャンセルする必要がある場合は、 `vserver migrate pause`そして `vserver migrate abort`コマンド。移行をキャンセルする前に一時停止する必要があります。カットオーバーの開始後は移行をキャンセルできません。

.結果
ストレージ VM はASAクラスタからASA r2 クラスタに移行されます。ストレージ VM の名前と UUID、データ LIF 名、IP アドレス、ボリューム名などのオブジェクト名は変更されません。ストレージ VM 内の移行されたオブジェクトの UUID が更新されます。

.次の手順
自動カットオーバーと自動ストレージVM削除を無効にした場合、link:svm-post-migrate-cutover-cleanup.html["ASAクライアントをASA r2 クラスタに手動で切り替え、 ASAクラスタからストレージ VM を削除します。"] 。
