---
sidebar: sidebar 
permalink: monitor/monitor-storage.html 
keywords: monitor, storage, cluster, utilization, usage 
summary: ストレージ利用率を監視して、現在および将来のワークロードに対応するために必要なストレージ容量を確保します。 
searchtitle: ONTAP System Managerを使用したスペース使用量の監視| ASA R2 
---
= ASA R2ストレージシステムでのクラスタおよびストレージユニットの使用率の監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Managerを使用してストレージ利用率を監視し、現在および将来のワークロードに対応するために必要なストレージ容量を確保します。



== クラスタ利用率の監視

クラスタで消費されるストレージの量を定期的に監視し、必要に応じてスペースが不足する前にクラスタの容量を拡張できるようにします。

.手順
. System Manager で、 * Dashboard * を選択します。
. [容量]*で、クラスタ上の使用済み物理スペースと使用可能なスペースを確認します。
+
データ削減率は、Storage Efficiencyによって削減されるスペースの量を表します。



.次の手順
クラスタのスペースが不足している場合や、クラスタに将来の需要を満たすための容量がない場合は、link:../administer/increase-storage-capacity.html["新しいドライブを追加"]ASA R2システムでストレージ容量を増やすことを計画する必要があります。



== ストレージアベイラビリティゾーンの使用状況の監視

ASA R2システムの各HAペアは、_ストレージ可用性ゾーン_と呼ばれる共通のストレージプールを使用します。ストレージのアベイラビリティゾーンは、ストレージシステム内の使用可能なすべてのディスクにアクセスでき、HAペアの両方のノードから認識できます。

クラスタにノードが4つ以上ある場合は、各HAペアのストレージアベイラビリティゾーンで使用されているスペースの量を表示できます。この指標は2ノードクラスタでは使用できません。

.手順
. System Managerで、*[クラスタ]*を選択し、*[概要]*を選択します。
+
クラスタ内の各HAペアについて、ストレージアベイラビリティゾーンの利用率の概要が表示されます。

. より詳細な指標が必要な場合は、特定のストレージの可用性を選択します。
+
[概要]*には、ストレージ可用性ゾーンの容量、使用済みスペース、およびデータ削減率が表示されます。

+
[ストレージユニット]*には、ストレージアベイラビリティゾーン内のすべてのストレージユニットのリストが表示されます。



.次の手順
ストレージ可用性ゾーンのスペースが不足している場合は、別のストレージ可用性ゾーンへの接続を計画して、クラスタ全体でストレージ利用率のバランスを調整する必要がありますlink:../manage-data/move-storage-units.html["ストレージユニットの移動"]。



== ストレージユニットの使用状況の監視

ビジネスニーズに基づいてストレージユニットのサイズをプロアクティブに拡張できるように、ストレージユニットが消費するストレージの量を監視します。

.手順
. System Managerで、*[ストレージ]*を選択します。
. 監視するストレージユニットを選択し、*[概要]*を選択します。
. [ストレージ]*で、次の情報を確認します。
+
** ストレージユニットのサイズ
** 使用済みスペースの量
** データ削減率
+
データ削減率は、Storage Efficiencyによって削減されたスペースを表します。

** Snapshot使用済み
+
[Snapshot Used]は、Snapshotで使用されているストレージの量を表します。





.次の手順
ストレージユニットの容量が上限に近づいている場合はlink:../manage-data/modify-storage-units.html["ストレージユニットの変更"]、サイズを大きくする必要があります。
