---
sidebar: sidebar 
permalink: administer/increase-storage-capacity.html 
keywords: increase, capacity, node, shelf, drive, expand, storage, asa r2, asa a1k, asa a90, asa a70 
summary: ノードまたはシェルフにドライブを追加して、ASA R2ストレージユニットの容量を増やします。 
---
= ASA R2ストレージシステムのストレージ容量を増やす
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードまたはシェルフにドライブを追加して、ASA R2システムのストレージ容量を増やします。



== NetApp Hardware Universeを使用して新しいドライブの設置を準備する

ノードまたはシェルフに新しいドライブを取り付ける前に、NetApp Hardware Universeを使用して、追加するドライブがASA R2プラットフォームでサポートされていることを確認し、新しいドライブ用の正しいスロットを特定します。ドライブを追加するための適切なスロットは、プラットフォームのモデルとONTAPのバージョンによって異なります。場合によっては、特定のスロットに順番にドライブを追加する必要があります。

.手順
. に移動しますlink:https://hwu.netapp.com/["NetApp Hardware Universe"^]。
. [製品]*で、ハードウェア構成を選択します。
. ASA R2プラットフォームを選択します。
. ONTAPのバージョンを選択し、*[結果を表示]*を選択します。
. 図の下にある* Click here to see alternative views *を選択し、設定に一致するビューを選択します。
. 構成のビューを使用して、新しいドライブがサポートされていること、および取り付け用の正しいスロットを確認します。


.結果
新しいドライブがサポートされていること、および取り付けに適したスロットがわかっていることを確認しておきます。



== ASA R2に新しいドライブを取り付ける

1回の手順で少なくとも6本のドライブを追加する必要があります。ドライブを1本追加するとパフォーマンスが低下する可能性があります。

.タスクの内容
この手順の手順は、ドライブごとに繰り返す必要があります。

.手順
. 自分自身を適切にアースします。
. プラットフォームの前面からベゼルをそっと取り外します。
. 新しいドライブを正しいスロットに挿入します。
+
.. カムハンドルが開いた状態で、両手で新しいドライブを挿入します。
.. ドライブが止まるまで押します。
.. ドライブがミッドプレーンに完全に収まり、カチッという音がして固定されるまで、カムハンドルを閉じます。
+
カムハンドルは、ドライブの前面に揃うようにゆっくりと閉じてください。



. ドライブのアクティビティLED（緑）が点灯していることを確認します。
+
** LEDが点灯している場合は、ドライブに電力が供給されています。
** LEDが点滅している場合は、ドライブに電力が供給されており、I/Oが実行中です。ドライブファームウェアの更新中もLEDが点滅します。
+
新しいドライブのファームウェアが最新バージョンでない場合は、自動的に更新されます（システムは停止されません）。



. ノードにドライブの自動割り当てが設定されている場合は、新しいドライブがONTAPによってノードに自動的に割り当てられるまで待つことができます。ノードでドライブの自動割り当てが設定されていない場合、または必要に応じて、ドライブを手動で割り当てることができます。
+
ノードに割り当てるまで新しいドライブは認識されません。



.次の手順
新しいドライブが認識されたら、ドライブが追加され、所有権が正しく指定されていることを確認します。
