---
sidebar: sidebar 
permalink: administer/rebalance-workloads.html 
keywords: rebalance workload, workload rebalancing, node balancing, asa r2 
summary: ONTAP 9.17.1 以降、 ONTAP はASA r2 システム HA ペアのノード間でワークロードを自動的に再調整し、パフォーマンスを最適化します。 
---
= ASA r2 ストレージ システム上のノード間でワークロードを再分散する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.17.1以降、 ONTAPはASA r2システムのHAペア内のノード間でワークロードを自動的にリバランスし、最適なパフォーマンスを実現します。例えば、一方のノードの使用率が70%に上昇したのに対し、そのHAペアのノードの使用率が30%にとどまっている場合、 ONTAPは各ノードの使用率がより均等になるようにワークロードを自動的にシフトします。HAペアのノードは同じストレージ・アベイラビリティ・ゾーンを共有しているため、ワークロードのリバランスはコピーフリーの操作であり、パフォーマンスに影響を与えません。



== 自動ワークロード再調整のデフォルトの評価期間を変更する

自動ワークロードリバランシングは、 ONTAP 9.17.1へのアップグレード後、または新しいONTAP 9.17.1 ASA r2クラスタの初期化後14日で、デフォルトで有効になります。ONTAPONTAPラインインターフェイス（CLI）を使用して、運用ニーズに合わせてデフォルトの評価期間を延長または短縮できます。

.手順
. 評価期間の残り日数を確認します。
+
[source, cli]
----
placement rebalance config show -fields evaluation-window
----
. リバランス評価期間を変更します。
+
[source, cli]
----
placement rebalance config modify -evaluation-window <number_of_evaluation_days>
----
+
次の例では、残りの評価期間を 10 日に設定します。

+
[listing]
----
placement rebalance config modify -evaluation-window 10
----




== 自動ワークロード再調整設定を変更する

自動ワークロードリバランシングは、 ONTAP 9.17.1へのアップグレード後、または新しいONTAP 9.17.1 ASA r2クラスタの初期化後14日で、デフォルトで有効になります。このデフォルト設定を変更して、自動ワークロードリバランシングを無効にしたり、アドバイザリ状態に設定して、不均衡なワークロードを自動的に移動せずにフラグ付けしたりすることができます。

.ステップ
. ノードに現在設定されている再バランス モードを確認します。
+
[source, cli]
----
placement rebalance config show -fields mode
----
. 自動ワークロード再バランス設定を変更します。
+
[source, cli]
----
placement rebalance config modify -mode <disabled|advisory|automated>
----
. 再バランスモードが変更されたことを確認します。
+
[source, cli]
----
placement rebalance config show -fields mode
----




== ワークロードの再バランスを手動でトリガーする

自動ワークロードリバランスを無効にしている場合でも、手動でワークロードリバランスをトリガーできます。これは、一定期間の手動調整後にワークロードをリバランスする場合や、リバランスモードを「アドバイザリ」に設定し、ワークロードフラグに基づいてアクションを実行したい場合に便利です。

.手順
. ノードに現在設定されている再バランス モードを確認します。
+
[source, cli]
----
placement rebalance config show -fields mode
----
. 再バランスモードが *advisory* に設定されていない場合は、*advisory* に設定します。
+
[source, cli]
----
placement rebalance config modify -mode advisory
----
. ワークロードの再バランスを手動でトリガーします。
+
[source, cli]
----
balanced-placement rebalance execute
----
. 再バランス操作のステータスを表示します。
+
[source, cli]
----
placement rebalance config show-evaluation
----


.次の手順
再調整モードを*自動*または*無効*に設定する場合は、  `placement rebalance config modify`指示。
