---
sidebar: sidebar 
permalink: administer/revert-ontap.html 
keywords: update, revert, ontap, asa r2 
summary: ASA r2 システムのONTAPソフトウェアの復元は、他のONTAPシステムの復元と同じプロセスに従います。ONTAPクラスタのリバートはシステム停止を伴います。 
---
= ASA r2 ストレージシステム上のONTAPを元に戻す
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2 システムのONTAPソフトウェアの復元は、他のONTAPシステムの復元と同じプロセスに従います。

ONTAPクラスターのリバートは、業務に影響を与えます。リバート作業中は、クラスターをオフラインにする必要があります。テクニカルサポートの支援なしに、本番環境のクラスターをリバートしないでください。新規クラスターやテスト用クラスターは、サポートなしでリバートできます。新しいシステムまたはテストシステムのリバートが失敗した場合、またはリバートは正常に完了したが、本番環境でのクラスターのパフォーマンスに満足できない場合は、テクニカルサポートにお問い合わせください。

完全な復元手順については、link:https://docs.netapp.com/us-en/ontap/revert/task_reverting_an_ontap_cluster.html["ONTAPクラスタのリバート"]を参照してください。



[[revert-requirements-for-asa-r2-systems]]
== ASA r2 システムの要件を元に戻す

特定のASA r2 クラスタ構成では、 ONTAPソフトウェアの復元を開始する前に特定のアクションを実行する必要があります。



[[reverting-from-ontap-9-17-1]]
=== ONTAP 9.17.1からの復元

ASA r2 システムでONTAP 9.17.1 から復元する場合は、復元を開始する前に次の操作を実行する必要があります。


NOTE: link:space-balancing.html["ダイナミックな空間バランス"]ONTAP 9.17.1 にアップグレードするか、新しいONTAP 9.17.1 ASA r2 クラスタを初期化してから 14 日後に、デフォルトで有効になります。動的スペース バランシングを有効にした後、 ASA r2 システムでONTAP 9.17.1 から戻すことはできません。

[cols="2"]
|===
| 構成 | 元に戻す前に、次の操作を行ってください... 


| SnapMirrorアクティブ同期関係における階層的整合性グループ | link:../data-protection/snapmirror-active-sync-delete-relationship.html["SnapMirrorのアクティブ同期関係を削除します"]。 


| アクティブなインポート関係 | アクティブなインポート関係を削除します。link:../install-setup/set-up-data-access.html#migrate-data-from-a-third-party-storage-system["輸入関係について学ぶ"]。 


| ランサムウェア対策が有効 | link:../secure-data/pause-resume-anti-ransomware-protection.html["ランサムウェア対策を一時停止する"]。 
|===