---
sidebar: sidebar 
permalink: administer/revert-ontap.html 
keywords: update, revert, ontap, asa r2 
summary: ONTAPは、ASA R2システムのファームウェアを自動的に更新します。System Managerを使用して、自動更新を無効にし、インストール前に更新を確認することができます。 
---
= ASA r2 ストレージシステム上のONTAPを元に戻す
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2 システムのONTAPソフトウェアの復元は、他のONTAPシステムの復元と同じプロセスに従います。

ONTAPクラスタのリバートはシステム停止を伴います。リバート中はクラスタをオフラインにする必要があります。本番環境のクラスタをリバートする場合は、テクニカルサポートの支援を受けてください。新規クラスタまたはテストクラスタは、支援を受けずにリバートできます。新規システムまたはテストシステムのリバートが失敗した場合、または正常に完了しても本番環境のクラスタのパフォーマンスに満足できない場合は、テクニカルサポートにご連絡ください。

link:https://docs.netapp.com/us-en/ontap/revert/task_reverting_an_ontap_cluster.html["ONTAPクラスタのリバート"] 。



== ASA r2 システムの要件を元に戻す

特定のASA r2 クラスタ構成では、 ONTAPソフトウェアの復元を開始する前に特定のアクションを実行する必要があります。



=== ONTAP 9.17.1からの復元

ASA r2 システムでONTAP 9.17.1 から復元する場合は、復元を開始する前に次の操作を実行する必要があります。


NOTE: link:../administer/rebalance-workloads.html["自動ワークロード再調整"]ONTAP 9.17.1 にアップグレードするか、新しいONTAP 9.17.1 ASA r2 クラスタを初期化してから 14 日後に、デフォルトで有効になります。自動ワークロード再バランスが有効になった後、 ASA r2 システムでONTAP 9.17.1 から復帰することはできません。

[cols="2"]
|===
| 構成 | 元に戻す前に、次の操作を行ってください... 


| SnapMirrorアクティブ同期関係における階層的整合性グループ | SnapMirrorのアクティブ同期関係を削除します 


| アクティブなインポート関係 | アクティブなインポート関係を削除する 


| ランサムウェア対策が有効 | ランサムウェア対策を無効にする 
|===