---
sidebar: sidebar 
permalink: administer/space-balancing.html 
keywords: capacity, space, rebalancing, balanced, placement, balance, asa r2 
summary: 組織の命名規則やその他の管理上の理由で、ノードの名前を変更しなければならない場合があります。 
---
= ASA r2 クラスタにおけるONTAP容量バランスについて学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2 システムの場合、 ONTAP はバランス配置を使用して、新しく作成されたストレージ ユニットを最適なストレージ可用性ゾーンに自動的に配置し、最適なパフォーマンスとバランスの取れたストレージ使用率を実現します。  ONTAP 9.17.1 以降を実行している場合、既存のストレージ ユニットによって消費されるスペースは、_動的スペース バランシング_ を使用してバランスが取られます。  ONTAP 9.16.1 を実行している場合、既存のストレージ ユニットによって消費されるスペースは、_コピーベースのワークロード再バランス_ を使用してバランス調整されます。

[cols="2"]
|===
| 機能 | ...でサポートされています 


| バランスの取れた配置 | ONTAP 9.16.1以降 


| ダイナミックな空間バランス | ONTAP 9.17.1以降 


| コピーベースのワークロード再バランス | ONTAP 9.16.1のみ 
|===
.バランスの取れた配置
_バランス配置_ により、新しく作成されたストレージ ユニットは、最適なパフォーマンスとバランスのとれたストレージ使用率を実現するために、最適なストレージ可用性ゾーン内に自動的に配置されます。  ONTAP 9.16.1 以降では、バランス配置がデフォルトで有効になっています。

.ダイナミックな空間バランス
_動的スペース バランシング_ により、 ONTAP はクラスタ内の空きスペースの量をアクティブに監視し、ストレージ アベイラビリティ ゾーン内でストレージ ユニットを自動的に移動して、スペース使用率のバランスを維持します。クラスター全体の容量使用率が 80% に達すると EMS 警告が自動的に発行され、90% に達すると EMS アラートが自動的に発行されます。

動的スペース バランシングは、 ONTAP 9.17.1 以降にアップグレードまたはインストールしてから 14 日後にデフォルトで有効になります。デフォルトの 14 日間の有効期間を変更する必要がある場合は、 NetAppサポートにお問い合わせください。動的スペースバランシングを有効にした後は、 ONTAP 9.17.1 から戻すことはできません。

動的スペース バランシングは、クラスター内のすべてのノードの空きスペースの全体的な平均 (グローバル平均) に基づいて、_通常モード_ または _低スペース モード_ のいずれかで動作します。

* *通常モード*
+
通常モードでは、 ONTAP は3 分ごとにチェックを行い、動的なスペース バランシングが必要かどうかを判断します。動的スペース バランシングは、次の条件が満たされる場合に通常モードで動作します。

+
** 空き領域の世界平均は 10% 以上です。
** クラスター内の少なくとも 1 つのノードに、グローバル平均よりも多くの空き領域があります。
** クラスター内の少なくとも 1 つのノードの空き容量が、グローバル平均よりも 20% 少なくなっています。


* *省スペースモード*
+
低スペース モードでは、 ONTAP は1 分ごとにチェックして、動的なスペース バランシングが必要かどうかを判断します。動的スペース バランシングは、次の条件が満たされる場合に低スペース モードで動作します。

+
** 空き領域の世界平均は 10% 未満です。
** クラスター内の少なくとも 1 つのノードに、グローバル平均よりも多くの空き領域があります。
** クラスター内の少なくとも 1 つのノードの空き容量がグローバル平均よりも少なくなっています。




.コピーベースのワークロード再バランス
_コピーベースのワークロード再バランス_ では、ストレージ アベイラビリティ ゾーン内でストレージ使用率の不均衡が発生した場合、 ONTAP は不均衡の原因となっているストレージ ユニットを、空き容量の多いストレージ アベイラビリティ ゾーンに自動的にコピーします。宛先ストレージ可用性ゾーンに十分な空き領域がない場合、 ONTAP はバランス調整アクションを実行しません。コピーベースのワークロード再バランスは、 ONTAP 9.16.1 を実行しているASA r2 システムにのみ適用され、これらのシステムではデフォルトで有効になっています。  ONTAP 9.17.1 以降では、動的スペース バランシングに置き換えられます。

コピーベースのワークロード再バランスのデフォルト設定を変更する必要がある場合は、 NetAppサポートにお問い合わせください。
