---
sidebar: sidebar 
permalink: administer/space-balancing.html 
keywords: capacity, space, rebalancing, balanced, placement, balance, asa r2 
summary: ASA r2システムの場合、ONTAPはバランスの取れた配置、動的なスペース バランシング、またはコピーベースのワークロード再バランシングを使用して、ストレージの可用性ゾーン全体でストレージ使用率をバランスよく維持します。 
---
= ASA r2 クラスタにおけるONTAP容量バランスについて学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2システムでは、ONTAPは_バランス配置_を使用して、新しく作成されたストレージユニットを最適なストレージの可用性ゾーンに自動的に配置し、最適なパフォーマンスとバランスの取れたストレージ利用を実現します。ONTAP 9.17.1以降を実行している場合、既存のストレージユニットが消費するスペースは、_動的スペースバランシング_を使用してバランス調整されます。ONTAP 9.16.1を実行している場合、既存のストレージユニットが消費するスペースは、_コピーベースのワークロード再バランシング_を使用してバランス調整されます。

[cols="2"]
|===
| 機能 | ...でサポートされています 


| バランスの取れた配置 | ONTAP 9.16.1以降 


| ダイナミックな空間バランス | ONTAP 9.17.1以降 


| コピーベースのワークロード再バランス | ONTAP 9.16.1のみ 
|===
.バランスの取れた配置
_バランスの取れた配置_では、新しく作成されたストレージユニットは、最適なパフォーマンスとバランスの取れたストレージ利用を実現するために、最適なストレージの可用性ゾーンに自動的に配置されます。バランスの取れた配置は、ONTAP 9.16.1以降ではデフォルトで有効になっています。

.ダイナミックな空間バランス
_ダイナミックスペースバランシング_により、ONTAPはクラスター内の空き容量を積極的に監視し、ストレージの可用性ゾーン内のストレージユニットを自動的に移動して、スペース利用のバランスを維持します。クラスタ全体の容量使用率が80%に達すると、イベント管理システム（EMS）の警告が自動的に発行され、90%に達するとEMSアラートが自動的に発行されます。

動的スペース バランシングは、 ONTAP 9.17.1 以降にアップグレードまたはインストールしてから 14 日後にデフォルトで有効になります。デフォルトの 14 日間の有効期間を変更する必要がある場合は、 NetAppサポートにお問い合わせください。動的スペースバランシングを有効にした後は、 ONTAP 9.17.1 から戻すことはできません。

動的スペース バランシングは、クラスター内のすべてのノードの空きスペースの全体的な平均 (グローバル平均) に基づいて、_通常モード_ または _低スペース モード_ のいずれかで動作します。

* *通常モード*
+
通常モードでは、 ONTAP は3 分ごとにチェックを行い、動的なスペース バランシングが必要かどうかを判断します。動的スペース バランシングは、次の条件が満たされる場合に通常モードで動作します。

+
** 空き領域の世界平均は 10% 以上です。
** クラスター内の少なくとも 1 つのノードに、グローバル平均よりも多くの空き領域があります。
** クラスター内の少なくとも 1 つのノードの空き容量が、グローバル平均よりも 20% 少なくなっています。


* *省スペースモード*
+
低スペース モードでは、 ONTAP は1 分ごとにチェックして、動的なスペース バランシングが必要かどうかを判断します。動的スペース バランシングは、次の条件が満たされる場合に低スペース モードで動作します。

+
** 空き領域の世界平均は 10% 未満です。
** クラスター内の少なくとも 1 つのノードに、グローバル平均よりも多くの空き領域があります。
** クラスター内の少なくとも 1 つのノードの空き容量がグローバル平均よりも少なくなっています。




.コピーベースのワークロード再バランス
_コピーベースのワークロード再バランス_ では、ストレージ アベイラビリティ ゾーン内でストレージ使用率の不均衡が発生した場合、 ONTAP は不均衡の原因となっているストレージ ユニットを、空き容量の多いストレージ アベイラビリティ ゾーンに自動的にコピーします。宛先ストレージ可用性ゾーンに十分な空き領域がない場合、 ONTAP はバランス調整アクションを実行しません。コピーベースのワークロード再バランスは、 ONTAP 9.16.1 を実行しているASA r2 システムにのみ適用され、これらのシステムではデフォルトで有効になっています。  ONTAP 9.17.1 以降では、動的スペース バランシングに置き換えられます。

コピーベースのワークロード再バランスのデフォルト設定を変更する必要がある場合は、 NetAppサポートにお問い合わせください。
