---
sidebar: sidebar 
permalink: administer/upgrade-ontap.html 
keywords: update, firmware, system files, automatic updates, automated updates, asa r2, disable, 
summary: ASA r2 システムのONTAPソフトウェア アップグレードは、他のONTAPシステムのアップグレードと同じプロセスに従います。  ASA r2 システムでONTAPソフトウェアをアップグレードすると、新しい ONTAP 機能と強化されたONTAP機能を利用できるようになります。 
---
= ASA R2ストレージシステムでのONTAPのアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA R2システムでONTAPソフトウェアをアップグレードすると、ONTAPの新機能や強化された機能を活用して、コストの削減、重要なワークロードの高速化、セキュリティの強化、組織で利用できるデータ保護の範囲の拡大を実現できます。

ASA r2 システムの ONTAP ソフトウェアアップグレードは、他の ONTAP システムのアップグレードと同じプロセスに従います。link:https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html["Active IQ Digital AdvisorのUpgrade AdvisorまたはUpgrade Health Checkerを使用してアップグレードの準備をする"^]から始めることをお勧めします。

アップグレードの準備ができたら、link:https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_sm.html["System Managerからの自動無停止アップグレード（ANDU）"^]を使用してアップグレードを実行することをお勧めします。ANDUでは、ONTAPのハイアベイラビリティ（HA）フェイルオーバー テクノロジを利用して、アップグレード中もクラスタからデータが提供されます。

link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["ONTAPソフトウェアのアップグレード"^]の詳細をご覧ください。



[[execute-automated-pre-upgrade-checks-before-a-planned-upgrade]]
== 自動アップグレード前チェックの実行 - 計画的アップグレード前

ONTAPソフトウェアのアップグレード プロセス中でなくても、ONTAPの自動アップグレード前チェックは実行できます。アップグレード前チェックをONTAPの自動アップグレード プロセスとは別に実行することで、クラスタに対して実行されたチェックを把握して、アップグレードを実際に開始する前に修正しておくべきエラーや警告のリストを入手できます。

ONTAP 9.19.1以降では、エラーと警告が個別に表示されるため、アップグレード前に解決する必要がある問題を簡単に特定できます。

link:https://docs.netapp.com/us-en/ontap/upgrade/automated-pre-checks.html["ONTAP 自動アップグレード前チェックを実行"^]方法をご確認ください。
