---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, learn more, learn about, get started 
summary: 'ASA r2 システム (ASA A1K、A90、A70、A50、A30、A20、C30) は、SAN のみの顧客向けに簡素化されたエクスペリエンスを実現する統合ハードウェアおよびソフトウェア ソリューションを提供します。' 
searchtitle: ASA A1K、A90、A70、A50、A30、A20、C30システムについて学ぶ 
---
= ASA R2ストレージシステムの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp ASA r2システムは、SANのみを利用するお客様にとって操作を簡素化する、統合されたハードウェアとソフトウェアのソリューションを提供します。ASA r2システムでは、ONTAPソフトウェアとSystem Managerが、SAN環境で不要な機能を削除しつつ、SANの必須機能をサポートするように合理化されています。

以下はASA r2 システムとして分類されます。

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30


.ストレージユニットと整合グループ
ASA R2システムでは、ストレージユニットとコンシステンシグループを使用できます。

* ストレージユニット_を指定すると、SANホストでデータ処理に使用できるストレージスペースが確保されます。ストレージユニットとは、SCSIホストの場合はLUN、NVMeホストの場合はNVMeネームスペースを指します。
* コンシステンシグループ_は、1つのユニットとして管理されるストレージユニットの集まりです。


ASA r2システムは、ストレージ管理とデータ保護を簡素化するために、整合性グループを備えたストレージユニットを使用します。例えば、整合性グループ内に10個のストレージユニットで構成されるデータベースがあり、そのデータベース全体をバックアップする必要があるとします。各ストレージユニットを個別にバックアップする代わりに、整合性グループをバックアップすることでデータベース全体を保護できます。

.データ保護とセキュリティ
盗難やランサムウェアなどの悪意のある攻撃からデータを保護するため、ASA r2システムは、オンボードのキーマネージャ、二重層暗号化、多要素認証、および複数管理者による検証をサポートしています。スナップショットをセカンダリの場所にレプリケートし、SnapLock for SnapVaultを使用して、宛先スナップショットが誤って、または悪意を持って削除されるのを防ぐこともできます。

.サポートされているプロトコル、マルチパス、および構成
ASA r2システムは、すべてのSANプロトコル（iSCSI、FC、NVMe/FC、NVMe/TCP）をサポートしています。すべてのプロトコルは、ホストとストレージ間のすべてのパスがアクティブかつ最適化されるよう、マルチパス向けの対称アクティブ / アクティブアーキテクチャをサポートしています。iSCSIおよびNVMe/TCPプロトコルは、サポートされているすべてのONTAPバージョンにおいて、ネットワーク構成および直接接続構成をサポートしています。FCおよびNVMe/FCプロトコルは、サポートされているすべてのONTAPバージョンにおいてネットワーク構成をサポートしており、ONTAP 9.19.1以降では直接接続構成もサポートしています。ASA r2システムは、ASA、AFF、またはFASシステムとのクラスター混在をサポートしていません。

* link:https://docs.netapp.com/us-en/ontap/san-admin/multipath-automatic-lif-failover-support.html["SANマルチパスサポート"^]の詳細をご覧ください。
* link:https://docs.netapp.com/us-en/ontap/san-config/configure-iscsi-san-hosts-ha-pairs-reference.html["iSCSIおよびNVMe/TCPプロトコルの設定"^]の詳細をご覧ください。
* link:https://docs.netapp.com/us-en/ontap/san-config/configure-fc-nvme-hosts-ha-pairs-reference.html["FCおよびNVMe/FCプロトコルの構成"^]の詳細をご覧ください。


.関連情報
* ASA R2システムのサポートおよび制限の詳細については、をlink:https://hwu.netapp.com/["NetApp Hardware Universe"^]参照してください。
* 詳細については、をご覧ください link:../learn-more/hardware-comparison.html["ASA R2システムとASAシステムの比較"]。
* の詳細については、をlink:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^]参照してください。

