---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa a90, asa a70, learn more, learn about, get started 
summary: ASA R2システム（ASA A1K、A90、A70）は、SANのみのお客様にシンプルなエクスペリエンスを提供する、ハードウェアとソフトウェアの統合ソリューションです。 
searchtitle: ASA A1K、A90、A70システムの詳細 
---
= ASA R2ストレージシステムの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp ASA R2システム（ASA A1K、ASA A70、およびASA A90）は、ハードウェアとソフトウェアの統合ソリューションを提供し、SANのみのお客様のニーズに合わせたシンプルな操作性を実現します。

ASA R2システムは、すべてのSANプロトコル（iSCSI、FC、NVMe/FC、NVMe/TCP）をサポートします。iSCSI、FC、NVMe/FCの各プロトコルでは、対称アクティブ/アクティブアーキテクチャのマルチパスがサポートされ、ホストとストレージ間のすべてのパスがアクティブ/最適化されます。iSCSIプロトコルとNVMe/TCPプロトコルは、ホストとストレージ間の直接パスをサポートします。

ASA R2システムでは、ONTAPソフトウェアとSystem Managerが合理化され、SAN環境でサポートされていない機能は削除されます。

ASA R2システムでは、ストレージユニットとコンシステンシグループを使用できます。

* ストレージユニット_を指定すると、SANホストでデータ処理に使用できるストレージスペースが確保されます。ストレージユニットとは、SCSIホストの場合はLUN、NVMeホストの場合はNVMeネームスペースを指します。
* コンシステンシグループ_は、1つのユニットとして管理されるストレージユニットの集まりです。


ASA R2システムは、ストレージユニットとコンシステンシグループを使用して、ストレージ管理とデータ保護を簡素化します。たとえば、10個のストレージユニットで構成されるデータベースが整合グループ内にあり、データベース全体をバックアップする必要があるとします。各ストレージユニットを個別にバックアップする代わりに、整合グループをバックアップすることでデータベース全体を保護できます。

盗難やランサムウェアなどの悪意のある攻撃からデータを保護するために、ASA R2システムはオンボードキーマネージャ、デュアルレイヤ暗号化、改ざん防止スナップショット、多要素認証、マルチ管理者検証をサポートしています。

ASA R2システムでは、現在のASA、AFF、またはFASシステムとのクラスタ混在はサポートされていません。

.詳細情報
* ASA R2システムのサポートおよび制限の詳細については、をlink:https://hwu.netapp.com/["NetApp Hardware Universe"^]参照してください。
* 詳細については、をご覧ください link:../learn-more/hardware-comparison.html["ASA R2システムとASAシステムの比較"]。
* の詳細については、をlink:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"]参照してください。

