---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, learn more, learn about, get started 
summary: 'ASA r2 システム (ASA A1K、A90、A70、A50、A30、A20、C30) は、SAN のみの顧客向けに簡素化されたエクスペリエンスを実現する統合ハードウェアおよびソフトウェア ソリューションを提供します。' 
searchtitle: ASA A1K、A90、A70、A50、A30、A20、C30システムについて学ぶ 
---
= ASA R2ストレージシステムの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp ASA R2システムは、ハードウェアとソフトウェアの統合ソリューションを提供し、SANのみのお客様のニーズに合わせたシンプルな操作性を実現します。

次のASAプラットフォームは、ASA R2システムに分類されます。

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30


ASA R2システムは、すべてのSANプロトコル（iSCSI、FC、NVMe/FC、NVMe/TCP）をサポートします。iSCSI、FC、NVMe/FC、NVMe/TCPの各プロトコルでは、対称アクティブ/アクティブアーキテクチャのマルチパスがサポートされ、ホストとストレージ間のすべてのパスがアクティブ/最適化されます。iSCSIプロトコルとNVMe/TCPプロトコルは、ホストとストレージ間の直接パスをサポートします。

ASA R2システムでは、ONTAPソフトウェアとSystem Managerが合理化され、SAN環境でサポートされていない機能は削除されます。

ASA R2システムでは、ストレージユニットとコンシステンシグループを使用できます。

* ストレージユニット_を指定すると、SANホストでデータ処理に使用できるストレージスペースが確保されます。ストレージユニットとは、SCSIホストの場合はLUN、NVMeホストの場合はNVMeネームスペースを指します。
* コンシステンシグループ_は、1つのユニットとして管理されるストレージユニットの集まりです。


ASA r2 システムは、一貫性グループを持つストレージ ユニットを使用して、ストレージ管理とデータ保護を簡素化します。たとえば、整合性グループ内の 10 個のストレージ ユニットで構成されるデータベースがあり、データベース全体をバックアップする必要があるとします。各ストレージ ユニットを個別にバックアップする代わりに、整合性グループをバックアップすることでデータベース全体を保護できます。

盗難やランサムウェアなどの悪意のある攻撃からデータを保護するために、ASA r2システムはオンボードキーマネージャー、二層暗号化、多要素認証、マルチ管理者認証をサポートしています。また、セカンダリASA r2システムでは改ざん防止スナップショットもサポートされています。

ASA R2システムでは、現在のASA、AFF、またはFASシステムとのクラスタ混在はサポートされていません。

.詳細情報
* ASA R2システムのサポートおよび制限の詳細については、をlink:https://hwu.netapp.com/["NetApp Hardware Universe"^]参照してください。
* 詳細については、をご覧ください link:../learn-more/hardware-comparison.html["ASA R2システムとASAシステムの比較"]。
* の詳細については、をlink:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"]参照してください。

