---
sidebar: sidebar 
permalink: data-protection/manage-consistency-groups.html 
keywords: consistency groups, snapshots, data protection, protect data, add, remove, delete, storage units, lun, namespace, increase capacity 
summary: 整合グループを使用すると、ユニットごとに個別に操作を実行するのではなく、複数のストレージユニットに対して同時にさまざまな操作を実行できます。 
---
= ASA r2 ストレージシステム上のONTAP整合性グループについて学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
整合性グループとは、単一のユニットとして管理されるストレージ ユニットの集合です。ストレージ管理を簡素化するには、整合性グループを使用します。

たとえば、整合性グループ内の 10 個のストレージ ユニットで構成されるデータベースがあり、データベース全体をバックアップする必要があるとします。各ストレージ ユニットをバックアップする代わりに、整合性グループにスナップショット データ保護を追加するだけで、データベース全体をバックアップできます。ストレージ ユニットを個別にバックアップするのではなく、一貫性グループとしてバックアップすると、すべてのユニットの一貫性のあるバックアップが提供されますが、ユニットを個別にバックアップすると不整合が生じる可能性があります。

ONTAP 9.16.1 以降では、System Manager を使用してASA r2 システムに階層型コンシステンシ グループを作成できます。階層構造では、1 つ以上の整合性グループが親整合性グループの下の子として構成されます。

階層型整合性グループを使用すると、各子整合性グループに個別のSnapshotポリシーを適用し、親をレプリケートしてすべての子整合性グループのSnapshotを1つのユニットとしてリモートクラスタにレプリケートできます。これにより、複雑なデータ構造のデータ保護と管理が簡易化されます。たとえば、という名前の親整合グループを作成し、このグループには、アプリケーションデータ用と `SVM1app_logs`アプリケーションログ用の2つの子整合グループが含まれている `SVM1app_data`とし `SVM1_app`ます。のスナップショット `SVM1app_data`は15分ごとに作成され、のスナップショット `SVM1app_logs`は1時間ごとに作成されます。親整合グループ `SVM1_app,`には、との `SVM1app_logs`両方のSnapshotを24時間ごとにリモートクラスタにレプリケートするSnapMirrorポリシーがあります。 `SVM1app_data`親整合グループは `SVM1_app`単一のユニットとして管理され、子整合グループは個別のユニットとして管理されます。



== レプリケーション関係における一貫性グループ

ONTAP 9.17.1 以降では、非同期レプリケーション関係またはSnapMirrorアクティブ同期関係内のコンシステンシ グループに対して、関係を破棄または削除することなく、次のジオメトリ変更を行うことができます。プライマリ整合性グループでジオメトリの変更が発生すると、その変更はセカンダリ整合性グループに複製されます。

* link:manage-consistency-groups-add-remove-storage-units.html["ストレージユニットのサイズを変更する"]ストレージユニットを追加または削除することによって。
* link:manage-hierarchical-consistency-groups.html#promote-an-existing-consistency-group-into-a-parent-consistency-group["単一の整合性グループを昇格する"]親整合性グループに追加します。
* link:manage-hierarchical-consistency-groups.html#demote-a-parent-consistency-group-to-a-single-consistency-group["親整合性グループを降格する"]単一の整合性グループに。
* link:manage-hierarchical-consistency-groups.html#detach-a-child-consistency-group-from-a-parent-consistency-group["子整合性グループの接続解除"]親整合性グループから。
* link:manage-hierarchical-consistency-groups.html#create-a-child-consistency-group["子整合グループを作成する"]既存の整合性グループを使用します。


ONTAP 9.16.1では、link:snapmirror-active-sync-break-relationship.html["非同期レプリケーション関係を解除する"]そしてlink:snapmirror-active-sync-delete-relationship.html["SnapMirrorのアクティブ同期関係を削除する"]整合性グループにジオメトリ変更を加える前に。
