---
sidebar: sidebar 
permalink: data-protection/snapshot-reserve.html 
keywords: asa r2, snapshot reserve, percentage 
summary: スナップショット予約とは、スナップショット専用に予約されているストレージ ユニット内のスペースの量です。スナップショットの自動削除でスナップショット予約が設定されている場合、スナップショットによって使用されるスペースがスナップショット予約を超えると、古いスナップショットが自動的に削除されます。 
---
= ASA r2ストレージのONTAPスナップショットリザーブについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スナップショット予約とは、スナップショット専用に予約されているストレージ ユニット内のスペースの量です。スナップショットの自動削除でスナップショット予約が設定されている場合、スナップショットによって使用されるスペースがスナップショット予約を超えると、古いスナップショットが自動的に削除されます。これにより、スナップショットがユーザー データ用のストレージ ユニット内のスペースを消費することがなくなります。

スナップショット予約は、ストレージ ユニットの合計サイズのパーセンテージとして設定されます。たとえば、ストレージ ユニットが 50 GB で、スナップショット予約を 10% に設定した場合、スナップショット用に予約される領域の量は 5 GB になります。スナップショットで使用されるスペースの量が 5 GB に達すると、新しいスナップショット用のスペースを確保するために古いスナップショットが自動的に削除されます。ストレージ ユニットのサイズが 100 GB に増加すると、スナップショット予約は 10 GB に増加します。設定できるスナップショット予約の最大値は 200% です。ストレージ ユニットが最大サイズの 128 TB まで拡張された場合、200% のスナップショット予約により、完全なスナップショットを 2 つ取得できます。

デフォルトでは、スナップショットの予約は 0% に設定されており、スナップショットの自動削除は有効になっていません。

ONTAP 9.18.1 以降では、ストレージ ユニットの作成中または作成後、およびコンシステンシー グループの作成中に、デフォルトのスナップショット リザーブを変更できます。既存のストレージ仮想マシン (VM) 上のデフォルトのスナップショット予約を変更することもできます。  ONTAP 9.17.1 以前では、これらの設定を変更することはできません。

スナップショット予約は、整合性グループの作成時に、整合性グループ内のすべてのストレージ ユニットに対して同じパーセンテージに設定されます。後で追加されるストレージ ユニットごとにスナップショット予約を個別に設定する必要があります。
